### ISSUE TITLE
Crear fichas para el segundo día

### ISSUE THREAD

**Issue by JJ** [oslugr/2017sereingeniera#1]
Con "refactorización" del baile, herramientas libres de dibujo y comienzo de Scratch/Lenguajes de bloques. Considerar quizás otra herramienta de programación con bloques más adecuada. Enganchar Scratch con la creación de rutinas de baile.

**Comment by JJ** [comment]
También @AIKUME puede hacer alguna, hay tres fichas en total.

**Comment by Makova** [comment]
Creada ficha de Scratch.
