### ISSUE TITLE
haacer ficha y presentación de github 

### ISSUE THREAD

**Issue by CristinaHG** [oslugr/2017sereingeniera#17]

**Comment by CristinaHG** [comment]
reasignando

**Comment by JJ** [comment]
Sorry...

El jueves, 22 de junio de 2017, Cristina Heredia <notifications@github.com>
escribió:
> Closed #17.
>
> —
> You are receiving this because you were assigned.
> Reply to this email directly, view it on GitHub, or mute the thread.<
https://ci5.googleusercontent.com/proxy/REO5DJYTGM2Ah5lpiGB-Xn5oT9AOLd1_7GcTlT-QanWiY5zrGfJ-aR-8XNlerVi_MQtbt1dHcv2jS88yvrV6tz1Wia70YqW-xouZm3bjEwJX6LYqufAooFi7I3EUeoSzAaMuCQdmUmmzOL3urh5KUdpxoOytMg=s0-d-e1-ft#https://github.com/notifications/beacon/AAAB9P2ptHGkUu0v_6P8k5tJUAhzGH97ks5sGqFAgaJpZM4N2zX2.gif
>

-- 
JJ
