### ISSUE TITLE
Recopilación de herramientas usadas en las diferentes fichas

### ISSUE THREAD

**Issue by JJ** [oslugr/2017sereingeniera#2]
Crear una página con todas las herramientas usadas por el momento (y en el futuro) para poder crear una distro a medida para que se use en el campus de chicas.

**Comment by JJ** [comment]
Esto le vendrá bien a @Makova para preparar la distro.

**Comment by Makova** [comment]
Claro que sí 😉

**Comment by Makova** [comment]
Preparada, @ireneherlo sabe como instalar algo por si hiciese falta. Aún así estaré yo también pendiente.
